### ISSUE TITLE
Error when start_driver.sh

### ISSUE THREAD

**Issue by serein-dream** [BUAA-BDA/OpenHuFu#174]
as title ,when i  run "./strat_driversh 1 2 3 4", i meet error as follow:
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/?useUnicode=true&useSSL=false
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at group.bda.federate.driver.PostgresqlServer$FederatePostgresqlService.init(PostgresqlServer.java:67)
	at group.bda.federate.driver.PostgresqlServer$FederatePostgresqlService.<init>(PostgresqlServer.java:59)
	at group.bda.federate.driver.PostgresqlServer.<init>(PostgresqlServer.java:386)
	at group.bda.federate.driver.PostgresqlServer.main(PostgresqlServer.java:399)

what should i do?
thanks! happy new year!

**Comment by serein-dream** [comment]
i have solved it! thanks
