### ISSUE TITLE
Knn error---spatial

### ISSUE THREAD

**Issue by serein-dream** [BUAA-BDA/OpenHuFu#175]
hi, could you give me some help?
when i  run distance query, it runs well
However, when i run knn query, it error as follows:

[grpc-default-executor-0] [INFO ] group.bda.federate.driver.MysqlServer.MysqlService - SELECT id,Distance(location, ST_GeomFromText('POINT(114.0 22.2)')) from osm_100w_3_1 WHERE TRUE ORDER BY  Distance(location, ST_GeomFromText('POINT(114.0 22.2)')) ASC  LIMIT 8
[grpc-default-executor-0] [INFO ] group.bda.federate.driver.MysqlServer.MysqlService - Execute SELECT id,Distance(location, ST_GeomFromText('POINT(114.0 22.2)')) from osm_100w_3_1 WHERE TRUE ORDER BY  Distance(location, ST_GeomFromText('POINT(114.0 22.2)')) ASC  LIMIT 8 returned 8 rows
[grpc-default-executor-0] [INFO ] group.bda.federate.driver.FederateDBService - DP delt = 0.0
Feb 18, 2024 5:26:27 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@60568811
org.apache.commons.math3.exception.NotStrictlyPositiveException: scale must be positive (0)
	at org.apache.commons.math3.distribution.LaplaceDistribution.<init>(LaplaceDistribution.java:73)
	at org.apache.commons.math3.distribution.LaplaceDistribution.<init>(LaplaceDistribution.java:58)
	at group.bda.federate.driver.FederateDBService.knnRadiusQuery(FederateDBService.java:544)
	at group.bda.federate.driver.FederateDBService.knnRadiusQuery(FederateDBService.java:434)
	at group.bda.federate.rpc.FederateGrpc$MethodHandlers.invoke(FederateGrpc.java:1028)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Looking for your help~

**Comment by SongY123** [comment]
Sorry for the late reply. You need to provide the error message from the server side; it looks like the error occurred on the server.
